server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000 #milliseconds
        response-timeout: 3s #Duration(sec)

resilience4j:
  circuitbreaker:
    instances:
      simpleCircuitBreaker:
        base-config: default
        sliding-window-size: 5
      simpleCircuitBreaker2:
        base-config: default
        sliding-window-size: 20
        failure-rate-threshold: 10
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        slow-call-rate-threshold: 90
        slow-call-duration-threshold: 3s
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: false
        permitted-number-of-calls-in-half-open-state: 5
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

  health:
    diskspace:
      enabled: false
    circuitbreakers:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

#  cloud:
#    gateway:
#      default-filters:
#        - name: GlobalFilter
#          args:
#            msg: "my cloud gateway filter"
#            preLog: true
#            postLog: true
#      routes:
#        - id: user-application
#          uri: lb://USER-APPLICATION
#          predicates:
#            - Path=/user-application/**
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-application/(?<segment>.*), /$\{segment}
#
#        - id: user-application
#          uri: lb://USER-APPLICATION
#          predicates:
#            - Path=/user-application/**
#            - Method=GET
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-application/(?<segment>.*), /$\{segment}
##            - name: AuthFilter
##            - name: CustomFilter
##            - name: LogFilter
##              args:
##                msg: log filter init
##                preLog: true
##                postLog: true
##            - AddRequestHeader=first-req, first-req-val
##            - AddResponseHeader=first-res, first-res-val
#
#        - id: user-application
#          uri: lb://USER-APPLICATION
#          predicates:
#            - Path=/user-application/actuator/**
#            - Method=POST, GET
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-application/(?<segment>.*), /$\{segment}