server:
  port: 8888

spring:
  application:
    name: client-two

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500ms
      retryExceptions:
        - com.app.clienttwo.RetryException
      ignoreExceptions:
        - com.app.clienttwo.IgnoreException
  instances:
    retryService:
      baseConfig: default
